### ISSUE TITLE
Resource Production Outposts

### ISSUE THREAD

**Issue by Steelwing723** [Sheeves11/UnnamedFiefdomGame#55]
Based on biomes surrounding fiefs. 
(Not sure if we should count diagonally adjacent spaces yet)

Adds the option to construct the following outposts based on the biomes surrounding a fief:

Farmland
> Produces: Food
> Unit(s): Farmer
> T1/T2/T3: Grange/Ranch/Estate

Mine
> Produces: Stone/Iron
> Unit(s): Miner
> T1/T2/T3: Stone Reserve/Rock Quarry/Mine Shafts

Lumber mill:
> Produces: Wood/Food
> Unit(s): Lumberjack/Hunter
> T1/T2/T3: Storages/Sawmill/Lumberyard

Fishery
> Produces: Food
> Unit(s): Fisher
> T1/T2/T3: Docks/Shacks/Boathouses

To simplify menus, only options available in fief surroundings should appear. 
Rather than have multiple menus for each outpost of the same type, one outpost menu should appear with the option to build additional outposts of the same type for each available spot. 

These new resources will be factored into the upgrade system and other future features.

**Comment by Sheeves11** [comment]
Great idea! I can't wait until this gets added

**Comment by Sheeves11** [comment]
Gonna close this for ya! Great work on these!
