### ISSUE TITLE
Stronghold Messages

### ISSUE THREAD

**Issue by Steelwing723** [Sheeves11/UnnamedFiefdomGame#56]
Allow players to set a stronghold message that enemy players can see when visiting that stronghold. 

This would just get added to the customizations menu along with changing the stronghold color.

**Comment by Sheeves11** [comment]
Great idea and pretty straightforward to implement! We're going to want to make sure we have some sort of input sanitation, as this will allow users to write directly to a file, which I hear can be dangerous.

**Comment by Sheeves11** [comment]
As far as input sanitation goes, we need to also limit message length

**Comment by Steelwing723** [comment]
Yep, I assumed around a 50 character message or so would suffice.
