### ISSUE TITLE
Add a list of conquered fiefdoms to the home stronghold screen

### ISSUE THREAD

**Issue by Sheeves11** [Sheeves11/UnnamedFiefdomGame#6]
This will require a loop that iterates through the /fiefs/ directory files and prints only the one where the player's username matches the file username field.

**Comment by Steelwing723** [comment]
Yup, display the number instead or it will likely get too long. I'll look into this.

**Comment by Sheeves11** [comment]
Update: Steelwing added this to the garrison screen!
